refactor: add missing overrides
Fixes instances of:
```bash
leveldb-subtree/db/log_test.cc:208:17: error: 'GetName' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
  208 |     std::string GetName() const { return ""; }
```